### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MTRNord** [GatoLoko/Wattpad2Epub#1]
Is it right that I have to change `initial_url` for changing the book and it would be nice to be able to have an argument where I can put it in

**Comment by GatoLoko** [comment]
You don't really need to edit the code to choose the book. If you look at lines 44-48, they deal with a parameter passed from command line. You can use it like this:

$ ./wattpad2epub http://www.wattpad.com/story/......

It's done that way (with http:// and all) so you can copy the address straight from your browser and paste it in the terminal.

The `initial_url` variable in line 52 is for testing purposes, to deal with a "known" scenario and find potential mistakes introduced when I change things. I just forgot to comment it out.

I'll comment it out, explain it's purpose in the comments and add a help parameter with usage instructions.

**Comment by GatoLoko** [comment]
Just committed a fix commenting out the line and adding a comment to make it usable for now. Will look into the help parameter and usage instructions later.

**Comment by GatoLoko** [comment]
I think it's all fixed now, with new comments, usage information and all.

**Comment by MTRNord** [comment]
Thanks for the Info :) I will close the issue
