### ISSUE TITLE
Download whole lists

### ISSUE THREAD

**Issue by ghost** [GatoLoko/Wattpad2Epub#13]
Example, be able to download everything from https://www.wattpad.com/list/999999999.

**Comment by rocketinventor** [comment]
And also, categories: i.e. https://www.wattpad.com/stories/humor.

Getting the list of books could be done either by parsing the `window.prefetched` object, or by finding all links that have `/story/*` in their URL (using `BeautifulSoup`).

A list of all book categories can be achieved by searching for all of the `/stories/*` URLs on the [Homepage ](https://www.wattpad.com/home)(all inside the `.discover-categories`  `div`).
