### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by vidupe** [GatoLoko/Wattpad2Epub#14]
New to this kinda thing, googled my way through it all. python wattpad2epub.py [link] won't work, so I added the directory of the file. I got this reaction:

> Traceback (most recent call last):
>   File "C:\Users\-\Desktop\Wattpad2Epub-master\wattpad2epub.py", line 282, in <module>
>     get_book(args.initial_url[0])
>   File "C:\Users\-\Desktop\Wattpad2Epub-master\wattpad2epub.py", line 214, in get_book
>     content=open("CSS/nav.css").read())
> FileNotFoundError: [Errno 2] No such file or directory: 'CSS/nav.css'

I got bs4, ebooklib and latest ver of python. anything wrong?

**Comment by GatoLoko** [comment]
It's a bug. You can see in that last line "CSS/nav.css" using / instead of \.

It should be an easy fix.

**Comment by GatoLoko** [comment]
It should be fixed now, but I don't have a Windows machine at hand to test it. Let me know if you try it.

**Comment by vidupe** [comment]
dled the latest file, but no, i still get the same error.

**Comment by GatoLoko** [comment]
I've tried it on a windows system and it works just as it's supposed to.

Are you sure you updated it with the last changes? If the error message is exactly the same it means you didn't update with the last changes.

**Comment by vidupe** [comment]
Well, it's my bad this time lol. I added directory by cd\ (I pasted it onto cmd line before) and it works just fine now.
