### ISSUE TITLE
Duplicate chapter name -> error in ePub

### ISSUE THREAD

**Issue by silbaer** [GatoLoko/Wattpad2Epub#19]
Creating a valid ePub fails, if duplicate chapter names exist:

```
C:\Program Files\Python38\lib\zipfile.py:1516: UserWarning: Duplicate name: 'EPUB/Frank.xhtml'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
```
Example: https://www.wattpad.com/story/54947779-%27normal%27-ist-relativ-solangelo

**Comment by GatoLoko** [comment]
Well, that's a poorly titled story, but alright, your patch has been merged, solving this.
