### ISSUE TITLE
The README.md needs some love.

### ISSUE THREAD

**Issue by GatoLoko** [GatoLoko/Wattpad2Epub#25]
As I have been made aware, the readme is a mess.

- The requirements section mentions how to install python on OSX, but nothing about windows or linux.

- The same requirement section explains one way to install beautifulsoup and ebooklib, does this work in windows? Should we mention other ways?

- Do we really want to explain how to install python and modules at all?

I'd really like to get some feedback about this.

**Comment by rocketinventor** [comment]
- The requirements install section is good to have, and it is the same process on Windows, too.
- When you are new to a project / just looking around, it is nice to have an easy to use guide.
- Many Wattpad users who find this project might be non-technical
- For the Python install instructions, just referencing the https://www.python.org/downloads/ link and/or various package managers that have it should be sufficient.

**Comment by GatoLoko** [comment]
> * The requirements install section is good to have, and it is the same process on Windows, too.

But the requirement section is a list of what we need, so any further instruction may be better placed in a different section, subsection or whatever.

> * When you are new to a project / just looking around, it is nice to have an easy to use guide.
> * Many Wattpad users who find this project might be non-technical

If you need a "easy to use guide", the current readme isn't good enough for you, and it must be improved. That's the point of this issue. How can we make it more useful for that kind of visitors?

> * For the Python install instructions, just referencing the https://www.python.org/downloads/ link and/or various package managers that have it should be sufficient.

That is "the windows way": go grab an installer in this-or-that web and run it, but not the right way to do it on linux/bsd/others for example. Maybe we should add an "installation guide" section, where we can tell them to grab the installer for windows, use brew for osx or use their linux/bsd distribution repositories.

The thing is, right now the instructions are incomplete and not very good.

**Comment by novasapper5431** [comment]
To install on windows, it only requires installing python from the Microsoft store. (Python 3.8 works for me and is the latest at the time of writing.) The rest of the commands are the same from then on. 

Edit: Git is also needed if you want to run everything from the command line at once, but both these installations are easy to do.
