### ISSUE TITLE
[ASK] can't we custom the filename output?

### ISSUE THREAD

**Issue by RubberArchind** [GatoLoko/Wattpad2Epub#26]

**Comment by GatoLoko** [comment]
What kind of customization are you thinking about?

Right now, the file name is composed by the title of the book and it's author, which seems like a very reasonable thing. What do you think is wrong with that?

**Comment by RubberArchind** [comment]
That's true, but I want to use this and send it to a user automatically when the download is complete, I'm having trouble getting the correct file name, can you guys please make some kind of callback for that?
Thanks in advance :)
