### ISSUE TITLE
no module named bs4

### ISSUE THREAD

**Issue by syerah** [GatoLoko/Wattpad2Epub#36]
Traceback (most recent call last):
  File "wattpad2epub.py", line 33, in <module>
    import gsweb
  File "C:\Users\User\Downloads\Wattpad2Epub-master\libs\gsweb.py", line 19, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

i've already tried the solution on Google but still no luck.

**Comment by GatoLoko** [comment]
The first thing that comes to mind is that you are using python2 which is no longer supported, or haven't installed the necessary beautifulsoup module.

Try installing it with:

`pip install beautifulsoup4`

**Comment by claudialorusso** [comment]
I don't know if it can still be helpful for someone but I solved this by using "pip3" instead of "pip".
