### ISSUE TITLE
Says gsweb not found what is gsweb

### ISSUE THREAD

**Issue by ND-451** [GatoLoko/Wattpad2Epub#38]

**Comment by Joeri-G** [comment]
gsweb.py is one of the libraries located in the lib folder, you need them to run the script.
```
Wattpad2Epub
├───CSS
├───HTML
└───libs
    └───gsweb.py
```

**Comment by ND-451** [comment]
The why does it say gsweb not found

**Comment by Joeri-G** [comment]
Maybe you didn't download it? can't say without logs
