### ISSUE TITLE
Installation is confusing

### ISSUE THREAD

**Issue by WavyDrip** [GatoLoko/Wattpad2Epub#41]
I have a problem with running program. I can't understand where should I input those commands:
```
pip3 install BeautifulSoup4
pip3 install ebooklib
```

And this comand as well:
`python3 wattpad2epub.py your_url_argument`

**Comment by novasapper5431** [comment]
These commands should be used in the command line (Powershell or CMD on windows and a terminal on Linux.) after installing python3 and pip3.

**Comment by GatoLoko** [comment]
It's a command line program, so a basic understanding of the command line is expected from the user, and it's not this programs mission to teach that.
[53f9e0a](https://github.com/GatoLoko/Wattpad2Epub/commit/53f9e0a69a3cff1b1f6f9d20625623e0d21513a8)
