### ISSUE TITLE
Remove forbidden characters from file names

### ISSUE THREAD

**Issue by ghost** [GatoLoko/Wattpad2Epub#8]
Currently if a title has for example "/' or ":" the epub file would not be created.

An easy fix would be just to change the following lines:

https://github.com/GatoLoko/Wattpad2Epub/blob/master/wattpad2epub.py#L172
https://github.com/GatoLoko/Wattpad2Epub/blob/master/wattpad2epub.py#L238

and remove the offending characters from string epubfile.

**Comment by GatoLoko** [comment]
It would be best to replace all characters susceptible of being problematic on file names.

Windows disallows the following characters: \/:*?"<>|

This affects FAT file systems used on pendrives and SD cards for many phones/tablets, and most probably other devices used to read epubs.

This list also covers the problematic "/" on Linux/Unix systems (including Android).
